### PR TITLE
Decouple from tk-bootstrap

### PR DESCRIPTION
**Pull request by GeorgeTaveras1231**
**Blocked on #16, ~~#17~~**

Goals
===
- De-couple styles from tk-bootstrap

Concerns
===
- Contributing to this project now requires access to our private npm registry.

Bugs
===
- ~~Label spacing is off by a pixel or two from working version~~

### CODE REVIEW

**Comment by GeorgeTaveras1231** [comment]
Not sure why the build is failing. Everything is passing locally.

**Comment by GeorgeTaveras1231** [comment]
Build is failing because of permission issues when trying to pull packages from gemfury

**Comment by jazzcrazed** [comment]
I would just add to the instructions to `npm login` for the XO Group Gemfury. Even though that dependency makes this far less useful to consume outside of XO, it's not revealing anything proprietary or vulnerable. Once that's set, I'm 👍

**Comment by GeorgeTaveras1231** [comment]
Thanks for the feedback @jazzcrazed. I updated the documentation on #16

**Comment by jazzcrazed** [comment]
👍  🚢

**Pull request merged**
